### ISSUE TITLE
Can't Compile Debian Buster 10.

### ISSUE THREAD

**Issue by kalpha2** [aligrudi/fbpdf#7]
Back again, maybe an install readme with dependencies listed would help etc?
I have done 
  git clone https://github.com/aligrudi/fbpdf.git
  make 2> mybuild.txt
and I get on screen
 cc -c -Wall -O2 -I./include fbpdf.c
 cc -c -Wall -O2 -I./include mupdf.c
 cc -c -Wall -O2 -I./include draw.c
 cc -o fbpdf fbpdf.o mupdf.o draw.o -L./lib -lmupdf -lmupdf-third -lmupdf-pkcs7 -lmupdf-threads -lm
and in mybuild.txt
  /usr/bin/ld: cannot find -lmupdf-pkcs7
  /usr/bin/ld: cannot find -lmupdf-threads
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:14: fbpdf] Error 1

if I remove -lmupdf-pkcs7 -lmupdf-threads get a load of undefined.
btw Buster is using mupdf 1.14 (whereas on Debian 9 I had issue with older muppdf)
There are no include, or lib folders.
Am I missing a step or a dependency?

**Comment by aligrudi** [comment]
kalpha2 <notifications@github.com> wrote:
> Back again, maybe an install readme with dependencies listed would help etc?
> I have done 
>   git clone https://github.com/aligrudi/fbpdf.git
>   make 2> mybuild.txt
> and I get on screen
>  cc -c -Wall -O2 -I./include fbpdf.c
>  cc -c -Wall -O2 -I./include mupdf.c
>  cc -c -Wall -O2 -I./include draw.c
>  cc -o fbpdf fbpdf.o mupdf.o draw.o -L./lib -lmupdf -lmupdf-third -lmupdf-pkcs7 -lmupdf-threads -lm
> and in mybuild.txt
>   /usr/bin/ld: cannot find -lmupdf-pkcs7
>   /usr/bin/ld: cannot find -lmupdf-threads
>   collect2: error: ld returned 1 exit status
>   make: *** [Makefile:14: fbpdf] Error 1
> 
> if I remove -lmupdf-pkcs7 -lmupdf-threads get a load of undefined.
> btw Buster is using mupdf 1.14 (whereas on Debian 9 I had issue with older muppdf)
> There are no include, or lib folders.
> Am I missing a step or a dependency?

What does the following command print?
  $ pkg-config --libs mupdf

By the way, another solution is compiling Mupdf yourself and copying
the .a libraries to the directory specified with -L.

	Ali

**Comment by kalpha2** [comment]
$pkg-config --libs mupdf
-lmupdf

I will look at compiling mupdf, I had to do that with Deb9 due to Mupdf being lower version, but Deb10 has 1.14 so was hoping would be okay

**Comment by kalpha2** [comment]
I pulled source for mupdf (version 1.14) and copy .a files as you said, now builds. thank you
