### ISSUE TITLE
Trying to switch tty while in fbpdf freezes system

### ISSUE THREAD

**Issue by g-w1** [aligrudi/fbpdf#9]
When you open a document in fbpdf and then try to switch ttys with alt arrow keys, it freezes up the system. I found that I had to force poweroff.

**Comment by aligrudi** [comment]
g-w1 <notifications@github.com> wrote:
> When you open a document in fbpdf and then try to switch ttys with
> alt arrow keys, it freezes up the system. I found that I had to force
> poweroff.

Unfortunately I cannot reproduce it.  Is it not possible to
switch to other TTYs to log in?

When switching TTYs SIGUSR1 and SIGUSR2 are sent to the
process controlling it.  Fbpad ignores these signals and
I cannot see how that leads to the problem.

	Ali

**Comment by g-w1** [comment]
I am using two monitors and fbpdf only displays on one of them. Maybe this is the problem. I'll try to disconnect one and see if that is the problem.
